targets:
  $default:
    sources:
      - e2e/**
      - test/**
    builders:
      bdd_widget_test|featureBuilder:
        options:
          stepFolderName: ../../../../test/cucumber_steps # this trick is required to share steps between widget and integration tests
          # testMethodName: customTestMethodName
