name: flutter_bloc_clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  theme:
    path: ../theme
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  uuid: ^3.0.6
  flow_builder: ^0.0.6
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  formz: ^0.4.1
  font_awesome_flutter: ^9.2.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  mocktail: ^0.3.0
  go_router: ^3.0.4
  very_good_analysis: ^2.4.0
  bdd_widget_test: ^1.3.0
  build_runner: ^2.1.8
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
